### ISSUE TITLE
Feature request: specify an open source license

### ISSUE THREAD

**Issue by nlebovits** [Vizzuality/global-ecosystems-atlas#57]
I found this through GEO's LinkedIn posts. The UI looks awesome. I run an open source project ([Clean & Green Philly](https://www.cleanandgreenphilly.org/)) that uses the same tech stack. I've asked our UX volunteers to draw some inspiration from the click-through tutorial when a user first lands on your map page. Assuming your code will remain open source, would you mind adding a license so we know what the restrictions are?

**Comment by d4weed** [comment]
In the meantime, we'll be making this repo temporarily private until we have a proper license in place.

Thanks again!
